name: GitHub Environments

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: production
      # this is a bogus url for now
      url: https://github.com

    steps:
      - name: 'Print secret from environment'
        run: |
          echo "APP_SECRET: ${{ secrets.APP_SECRET }}"
